// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<Error>;

export function OpenFile(arg1:string):Promise<Error>;

export function OpenInBrowser(arg1:string):Promise<Error>;

export function RootItems():Promise<Array<main.ListItem>>;

export function RunListCommand(arg1:string):Promise<main.ScriptResponse>;

export function RunScript(arg1:string,arg2:Array<string>):Promise<Error>;
