// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function RootItems() {
  return window['go']['main']['App']['RootItems']();
}

export function RunListCommand(arg1) {
  return window['go']['main']['App']['RunListCommand'](arg1);
}

export function RunScript(arg1, arg2) {
  return window['go']['main']['App']['RunScript'](arg1, arg2);
}
